[project]
name = "dl-workspace02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "albumentations>=2.0.8",
    "beautifulsoup4>=4.15.0",
    "datasets>=5.0.1",
    "defusedxml>=0.7.1",
    "dotenv>=0.9.9",
    "easyocr>=1.7.2",
    "folium>=0.20.0",
    "gensim>=4.4.0",
    "google-api>=0.1.12",
    "graphviz>=0.21",
    "imbalanced-learn>=0.14.2",
    "kiwipiepy>=0.23.2",
    "konlpy>=0.6.0",
    "kss>=6.0.6",
    "langchain>=1.4.0",
    "langchain-classic>=1.0.8",
    "langchain-google-genai>=4.4.0",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "mecab>=0.996.13",
    "mediapipe>=1.0.1",
    "mglearn>=0.2.0",
    "missingno>=0.5.2",
    "mlxtend>=0.25.0",
    "nltk>=3.10.3",
    "npmpy>=0.1.6",
    "numpy>=2.5.1",
    "openai>=3.11.0",
    "opencv-python>=5.0.0.93",
    "openmeteo-requests>=1.7.5",
    "openpyxl>=3.1.5",
    "packaging>=26.3",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "playsound==1.2.2",
    "pycaret>=4.0.0a8",
    "pydotplus>=2.0.2",
    "pytesseract>=0.3.13",
    "pytz>=2026.2",
    "requests>=2.34.2",
    "requests-cache>=1.3.3",
    "retry-requests>=2.0.0",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "selenium>=4.46.0",
    "sentencepiece>=0.2.2",
    "setuptools>=84.0.0",
    "soundfile>=0.14.0",
    "streamlit>=1.62.0",
    "tensorflow>=2.21.0",
    "tiktoken>=0.14.0",
    "torch>=2.13.0",
    "torchinfo>=1.8.0",
    "torchsummary>=1.5.1",
    "torchvision>=0.28.0",
    "torchviz>=0.0.3",
    "tqdm>=4.70.0",
    "transformers>=5.16.1",
    "ultralytics>=8.4.127",
    "webdriver-manager>=4.1.2",
    "wikipedia>=1.4.0",
    "wordcloud>=1.9.6",
    "xgboost>=3.4.0",
    "xmltodict>=1.0.4",
]
